"""Central optimization and standalone-link policy for generated Fortran."""

from __future__ import annotations

import os
from pathlib import Path


def is_gnu_fortran(compiler: str) -> bool:
    return "gfortran" in Path(compiler).name.casefold()


def aggressive_fortran_flags(compiler: str) -> tuple[str, ...]:
    """High optimization without relaxing IEEE/NaN program semantics."""

    name = Path(compiler).name.casefold()
    if "gfortran" in name:
        return (
            "-O3", "-march=native", "-flto", "-funroll-loops",
            "-fomit-frame-pointer",
        )
    if name.startswith(("ifx", "ifort")):
        return ("-O3", "-xHost", "-ipo")
    if "flang" in name:
        return ("-O3", "-march=native", "-flto")
    return ("-O3",)


def aggressive_c_flags(fortran_compiler: str) -> tuple[str, ...]:
    """C-host flags compatible with the selected Fortran link driver."""

    if is_gnu_fortran(fortran_compiler):
        return (
            "-O3", "-march=native", "-flto", "-funroll-loops",
            "-fomit-frame-pointer",
        )
    return ("-O3",)


def standalone_fortran_link_flags(compiler: str) -> tuple[str, ...]:
    """Link compiler runtimes into the artifact instead of requiring DLLs."""

    if not is_gnu_fortran(compiler):
        raise ValueError(
            "standalone runtime linkage is currently defined only for GNU "
            "Fortran; set standalone=False or add a verified compiler policy"
        )
    flags = ["-flto", "-static-libgfortran", "-static-libgcc"]
    if os.name == "nt":
        # This also selects archive forms of libquadmath and transitive GNU
        # support libraries. Windows system DLLs remain normal OS ABI imports.
        flags.append("-static")
    return tuple(flags)


# libgfortran's ``string.o`` (pulled in by any module that touches the string
# or formatted-I/O runtime) calls ``strndup``.  A mingw-w64 CRT older than the
# installed gcc does not define it, so a ``-static`` link fails to resolve it
# while a DLL-runtime link never pulls the object at all.  Supplying our own
# definition satisfies the reference; the CRT's own archive member, if a later
# CRT has one, is then simply never pulled, so this cannot collide.  No header
# is included, so no platform prototype can conflict with it either.  The
# definition is WEAK so that a newer CRT's strong strndup (or another shim that
# also carries one, e.g. the C shell's) overrides it instead of colliding: with
# GCC 16's mingw the CRT began providing strndup, and two strong definitions in
# the same link multiply-define the symbol.
_CRT_SHIM_SOURCE = """\
/* Generated by turing's Fortran toolchain policy.  See fortran_toolchain.py. */
#include <stdlib.h>

__attribute__((weak)) char *strndup(const char *s, size_t n)
{
    size_t len = 0;
    size_t i;
    char *out;

    while (len < n && s[len] != '\\0') {
        len++;
    }
    out = (char *)malloc(len + 1);
    if (out == NULL) {
        return NULL;
    }
    for (i = 0; i < len; i++) {
        out[i] = s[i];
    }
    out[len] = '\\0';
    return out;
}
"""


def standalone_runtime_shim_sources(
    compiler: str, directory: Path, standalone: bool = True
) -> tuple[str, ...]:
    """Emit CRT sources a standalone GNU link needs but this CRT lacks."""

    if not standalone or os.name != "nt" or not is_gnu_fortran(compiler):
        return ()
    path = Path(directory) / "turing_crt_shim.c"
    path.write_text(_CRT_SHIM_SOURCE, encoding="utf-8")
    return (str(path),)


__all__ = [
    "aggressive_c_flags",
    "aggressive_fortran_flags",
    "is_gnu_fortran",
    "standalone_fortran_link_flags",
    "standalone_runtime_shim_sources",
]
