"""Generate and run Python host shells from compiled IO descriptors.

This module is application-blind.  It knows the physical shell resources
defined by ``shell_io.py`` and the calling convention in
``compiled_program_api.py``; it does not know Mandelbrot, cursor toys, or any
other program.  A generated launcher contains only paths and descriptors.
"""

from __future__ import annotations

import argparse
import ctypes
from dataclasses import dataclass
import json
import math
import os
from pathlib import Path
import re
import time
from typing import Any, Callable, Mapping, Sequence
import hashlib

import numpy as np


_CTYPES = {
    "c_bool": ctypes.c_bool,
    "c_float": ctypes.c_float,
    "c_double": ctypes.c_double,
    "c_int32": ctypes.c_int32,
    "c_int64": ctypes.c_int64,
    "c_uint8": ctypes.c_uint8,
}
_DTYPES = {
    "c_bool": np.dtype("bool"),
    "c_float": np.dtype("float32"),
    "c_double": np.dtype("float64"),
    "c_int32": np.dtype("int32"),
    "c_int64": np.dtype("int64"),
    "c_uint8": np.dtype("uint8"),
}

_RUNTIME_OPTION_NAMES = {
    "frames", "headless", "profile", "profile_ignore_transfer",
    "profile_warmup",
}


def _file_option_name(port_name: str) -> str:
    return "file_port__" + re.sub(r"[^A-Za-z0-9_]", "_", str(port_name))


@dataclass(frozen=True)
class NativeFilePortValue:
    name: str
    path: Path
    data: np.ndarray

    @property
    def byte_length(self) -> int:
        return int(self.data.size)


class NativeFilePortHandler:
    """Resolve descriptor-declared file ports to stable native byte storage."""

    def __init__(self, manifest: Mapping[str, Any], options: Mapping[str, Any]):
        self.values: dict[str, NativeFilePortValue] = {}
        for port in manifest.get("system_ports", ()):
            if port.get("kind") != "file" or port.get("direction") not in {
                "input", "bidirectional",
            }:
                continue
            name = str(port["name"])
            supplied = options.get(_file_option_name(name))
            if not supplied:
                if port.get("optional"):
                    continue
                raise ValueError(f"native shell requires file port {name!r}")
            path = Path(str(supplied)).resolve()
            if not path.is_file():
                raise ValueError(f"native file port {name!r} is not a file: {path}")
            data = np.frombuffer(path.read_bytes(), dtype=np.uint8).copy()
            self.values[name] = NativeFilePortValue(name, path, data)

    def resource(self, port_name: str, field: str) -> Any:
        value = self.values.get(port_name)
        if value is None:
            raise KeyError(f"native file port {port_name!r} has no supplied value")
        if field == "data":
            return value.data
        if field == "length":
            return value.byte_length
        raise KeyError(f"native file port {port_name!r} has no field {field!r}")


@dataclass(frozen=True)
class ArrivalProfile:
    """Completion-gap measurements for a generated native entry point."""

    arrivals: int
    warmup: int
    transfer_excluded: bool
    gaps_ms: tuple[float, ...]

    def to_mapping(self) -> dict[str, Any]:
        gaps = np.asarray(self.gaps_ms, dtype=np.float64)
        return {
            "schema": "turing-native-arrival-profile-v1",
            "arrivals": self.arrivals,
            "warmup": self.warmup,
            "transfer_excluded": self.transfer_excluded,
            "measurement_boundary": (
                "execution_completion"
                if self.transfer_excluded else "display_plane_arrival"
            ),
            "gap_ms": {
                "minimum": float(np.min(gaps)),
                "median": float(np.median(gaps)),
                "mean": float(np.mean(gaps)),
                "p95": float(np.percentile(gaps, 95)),
                "maximum": float(np.max(gaps)),
            },
            "arrivals_per_second": float(1000.0 / np.mean(gaps)),
        }


@dataclass(frozen=True)
class GeneratedPythonShell:
    source: str

    def write(self, path: str | Path) -> Path:
        destination = Path(path)
        destination.parent.mkdir(parents=True, exist_ok=True)
        destination.write_text(self.source, encoding="utf-8")
        return destination


def emit_python_native_shell(
    api: Any,
    library_path: str | Path,
) -> GeneratedPythonShell:
    """Emit a launch script entirely from an attached compiled descriptor."""

    mapping = api.to_mapping() if hasattr(api, "to_mapping") else dict(api)
    shell_io = (mapping.get("metadata") or {}).get("shell_io")
    if not shell_io:
        raise ValueError("compiled API has no attached shell IO contract")
    payload = json.dumps(mapping, sort_keys=True)
    library = json.dumps(str(Path(library_path).resolve()))
    package_root = json.dumps(str(Path(__file__).resolve().parents[2]))
    source = f'''# Generated by src.compiler.python_native_shell; do not edit.
import json
import sys

sys.path.insert(0, {package_root})
from src.compiler.python_native_shell import launch_native_shell

COMPILED_API = json.loads({payload!r})
LIBRARY_PATH = {library}

if __name__ == "__main__":
    raise SystemExit(launch_native_shell(COMPILED_API, LIBRARY_PATH))
'''
    return GeneratedPythonShell(source)


@dataclass(frozen=True)
class CompiledNativeShell:
    module: Any
    library_path: Path
    launcher_path: Path


def _compile_time_resource(
    resource: str,
    options: Mapping[str, Any],
) -> Any:
    width = int(options.get("width", 640))
    height = int(options.get("height", 480))
    if resource == "display.unit_x":
        row = np.linspace(-1.0, 1.0, width, dtype=np.float32)
        return np.ascontiguousarray(np.tile(row, height))
    if resource == "display.unit_y":
        column = np.linspace(-1.0, 1.0, height, dtype=np.float32)
        return np.ascontiguousarray(np.repeat(column, width))
    if resource == "clock.seconds":
        return np.float64(0.0)
    if resource.startswith("option."):
        return options[resource.split(".", 1)[1]]
    if resource in {"pointer.x", "pointer.y"}:
        return np.float64(0.0)
    if resource in {"pointer.buttons", "keyboard.bits"}:
        return np.int32(0)
    raise ValueError(f"cannot synthesize compile-time probe for {resource!r}")


def compile_ast_fortran_io_shell(
    source: str,
    entrypoint: str,
    manifest: Any,
    options: Mapping[str, Any],
    *,
    directory: str | Path | None = None,
) -> CompiledNativeShell:
    """Compile and generate one native shell using only declarative IO."""

    from ..common.tensors.accelerator_backends.aot_compile import compile_ast_aot
    from .backend_sources import collect_backend_sources
    from .shell_io import attach_shell_io
    from .ssa_fortran_backend import FortranModule, compile_module

    manifest = manifest.specialize_options(options)
    feeds = {
        binding.parameter: _compile_time_resource(binding.resource, options)
        for binding in manifest.bindings
        if binding.resource != "display.back"
    }
    aot = compile_ast_aot(
        source,
        entrypoint,
        feeds,
        backend="fortran",
        precompile_only=True,
    )
    program = getattr(
        aot.compiled_shell_program, "program", aot.compiled_shell_program
    )
    sources = collect_backend_sources(
        aot,
        numerical_name=f"{entrypoint}_numerical",
        control_name=entrypoint,
        program=program,
    )
    emitted = next(item for item in sources.sources if item.language == "fortran")
    if not emitted.available or emitted.artifact is None:
        raise RuntimeError(f"Fortran IO compilation failed: {emitted.reason}")
    original = emitted.artifact
    module = FortranModule(
        original.name,
        original.source,
        original.subroutines,
        api=attach_shell_io(original.api, manifest),
    )
    if directory is None:
        specialization = json.dumps(dict(options), sort_keys=True, default=str)
        descriptor = json.dumps(
            module.api.to_mapping(), sort_keys=True, default=str
        )
        digest = hashlib.sha256(
            (
                source + entrypoint + specialization
                + module.source + descriptor
            ).encode("utf-8")
        ).hexdigest()[:16]
        directory = (
            Path(__file__).resolve().parents[2]
            / ".turing-cache" / "native_shells" / f"{entrypoint}_{digest}"
        )
    output_directory = Path(directory).resolve()
    output_directory.mkdir(parents=True, exist_ok=True)
    library = compile_module(module, directory=output_directory)
    launcher = emit_python_native_shell(module.api, library).write(
        output_directory / f"run_{entrypoint}.py"
    )
    return CompiledNativeShell(module, library, launcher)


def compile_and_launch_ast_fortran_io(
    source: str,
    entrypoint: str,
    manifest: Any,
    argv: Sequence[str] | None = None,
) -> int:
    """Parse generated options, compile the specialization, and run it."""

    parsed = _option_parser(manifest.to_mapping()).parse_args(argv)
    values = vars(parsed)
    compile_options = {
        key: value for key, value in values.items()
        if key not in _RUNTIME_OPTION_NAMES and not key.startswith("file_port__")
    }
    compiled = compile_ast_fortran_io_shell(
        source, entrypoint, manifest, compile_options
    )
    return launch_native_shell(
        compiled.module.api,
        compiled.library_path,
        argv=argv,
    )


def _entry(api: Mapping[str, Any], name: str | None = None) -> Mapping[str, Any]:
    selected = name or api.get("entry")
    matches = [
        item for item in api.get("entry_points", ()) if item.get("name") == selected
    ]
    if len(matches) != 1:
        raise ValueError(f"compiled API has no unique entry point {selected!r}")
    return matches[0]


def _option_parser(manifest: Mapping[str, Any]) -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description="generated native IO shell")
    types = {"int": int, "float": float, "str": str}
    for option in manifest.get("options", ()):
        flag = "--" + str(option["name"]).replace("_", "-")
        if option["type"] == "bool":
            parser.add_argument(flag, action="store_true", default=option["default"])
        else:
            parser.add_argument(
                flag,
                type=types[option["type"]],
                default=option["default"],
                help=option.get("help") or None,
            )
    for port in manifest.get("system_ports", ()):
        if port.get("kind") != "file" or port.get("direction") not in {
            "input", "bidirectional",
        }:
            continue
        name = str(port["name"])
        parser.add_argument(
            "--file-" + name.replace("_", "-"),
            dest=_file_option_name(name),
            required=not bool(port.get("optional")),
            help="path supplied to the " + name + " file system port",
        )
    parser.add_argument("--frames", type=int, default=0)
    parser.add_argument("--headless", action="store_true")
    parser.add_argument(
        "--profile", action="store_true",
        help="run headlessly and report completed-generation arrival gaps",
    )
    parser.add_argument(
        "--profile-ignore-transfer", action="store_true",
        help=(
            "measure execution completions without acquiring the display plane; "
            "this excludes device-to-host/PCIe readback when the runtime has one"
        ),
    )
    parser.add_argument("--profile-warmup", type=int, default=3)
    return parser


class NativeShellRuntime:
    """Descriptor-driven native call, IO resources, and double buffer."""

    def __init__(
        self,
        api: Mapping[str, Any],
        library_path: str | Path,
        options: Mapping[str, Any],
    ):
        if hasattr(api, "to_mapping"):
            api = api.to_mapping()
        self.api = dict(api)
        self.contract = self.api["metadata"]["shell_io"]
        self.manifest = self.contract["requirements"]
        self.options = dict(options)
        bindings = self.manifest.get("bindings", ())
        system_ports = self.manifest.get("system_ports", ())
        entry_names = {binding["entry_point"] for binding in bindings}
        entry_names.update(
            str(port["entry_point"])
            for port in system_ports if port.get("entry_point")
        )
        if len(entry_names) != 1:
            raise ValueError("generated native shell requires one bound entry point")
        self.entry = _entry(self.api, next(iter(entry_names)))
        self.bindings = {
            binding["parameter"]: binding["resource"] for binding in bindings
        }
        self.system_fields = {
            str(field["parameter"]): (str(port["name"]), str(field["name"]))
            for port in system_ports
            for field in port.get("fields", ())
        }
        self.file_ports = NativeFilePortHandler(self.manifest, self.options)
        self.width = int(self.options.get("width", 640))
        self.height = int(self.options.get("height", 480))
        if self.width < 2 or self.height < 2:
            raise ValueError("display width and height must both be at least 2")
        self.pointer = [0.0, 0.0]
        self.buttons = 0
        self.keys = 0
        self.front = 0
        self.generation = 0
        self._resource_cache: dict[str, Any] = {}
        self._outputs: dict[str, list[np.ndarray]] = {}
        for parameter in self.entry["parameters"]:
            resource = self.bindings.get(parameter["name"], "")
            if parameter["role"] != "output" or not resource.startswith("display."):
                continue
            shape = tuple(parameter.get("shape") or (self.width * self.height,))
            dtype = _DTYPES[parameter["ctypes"]]
            self._outputs[parameter["name"]] = [
                np.empty(shape, dtype=dtype), np.empty(shape, dtype=dtype)
            ]
        has_display = any(
            request.get("capability") == "display_double_buffer"
            for request in self.manifest.get("requests", ())
        )
        if has_display and not self._outputs:
            raise ValueError("display capability has no bound output parameter")
        display = next((
            request for request in self.manifest["requests"]
            if request["capability"] == "display_double_buffer"
        ), None)
        if display is None:
            self._dll_directory = None
            self.library = ctypes.CDLL(str(Path(library_path).resolve()))
            self.native = getattr(self.library, self.entry["symbol"])
            return
        pixel_format = (display.get("attributes") or {}).get(
            "pixel_format", "rgba8"
        )
        components = {"indexed_float32": 1, "rgb8": 3, "rgba8": 4}.get(
            pixel_format
        )
        if components is None:
            raise ValueError(f"unsupported generated display format {pixel_format!r}")
        expected_size = self.width * self.height * components
        for buffers in self._outputs.values():
            if buffers[0].size != expected_size:
                raise ValueError(
                    "compiled display extent does not match the requested size: "
                    f"artifact has {buffers[0].size} values, shell needs "
                    f"{expected_size}"
                )
        self._dll_directory = None
        from .ssa_fortran_backend import fortran_compiler

        compiler = fortran_compiler()
        if os.name == "nt" and hasattr(os, "add_dll_directory") and compiler:
            self._dll_directory = os.add_dll_directory(str(Path(compiler).parent))
        self.library = ctypes.CDLL(str(Path(library_path).resolve()))
        self.native = getattr(self.library, self.entry["symbol"])

    def _resource(self, name: str, elapsed: float) -> Any:
        if name == "clock.seconds":
            return float(elapsed)
        if name == "display.unit_x":
            if name in self._resource_cache:
                return self._resource_cache[name]
            row = np.linspace(-1.0, 1.0, self.width, dtype=np.float32)
            value = np.ascontiguousarray(np.tile(row, self.height))
            self._resource_cache[name] = value
            return value
        if name == "display.unit_y":
            if name in self._resource_cache:
                return self._resource_cache[name]
            column = np.linspace(-1.0, 1.0, self.height, dtype=np.float32)
            value = np.ascontiguousarray(np.repeat(column, self.width))
            self._resource_cache[name] = value
            return value
        if name == "pointer.x":
            return float(self.pointer[0])
        if name == "pointer.y":
            return float(self.pointer[1])
        if name == "pointer.buttons":
            return int(self.buttons)
        if name == "keyboard.bits":
            return int(self.keys)
        if name.startswith("option."):
            return self.options[name.split(".", 1)[1]]
        raise KeyError(f"native shell does not provide resource {name!r}")

    def _parameter_resource(self, parameter_name: str, elapsed: float) -> Any:
        system = self.system_fields.get(parameter_name)
        if system is not None:
            return self.file_ports.resource(*system)
        resource = self.bindings.get(parameter_name)
        if resource is None:
            raise ValueError(f"unbound native input {parameter_name!r}")
        return self._resource(resource, elapsed)

    def execute(self, elapsed: float) -> int:
        """Complete one compiled generation without acquiring its display plane."""

        arguments = []
        argument_types = []
        back = 1 - self.front
        for parameter in self.entry["parameters"]:
            ctype = _CTYPES[parameter["ctypes"]]
            if parameter["role"] == "extent":
                extent = int(parameter["name"].rsplit("_", 1)[-1])
                arguments.append(ctype(extent))
                argument_types.append(ctype)
                continue
            resource = self.bindings.get(parameter["name"])
            if parameter["role"] == "output":
                if parameter["name"] not in self._outputs:
                    raise ValueError(
                        f"unbound non-display output {parameter['name']!r}"
                    )
                value = self._outputs[parameter["name"]][back]
            else:
                value = self._parameter_resource(parameter["name"], elapsed)
            if parameter["passing"] == "value":
                arguments.append(ctype(value))
                argument_types.append(ctype)
            else:
                array = np.asarray(value, dtype=_DTYPES[parameter["ctypes"]])
                if not array.flags.c_contiguous:
                    array = np.ascontiguousarray(array)
                arguments.append(array.ctypes.data_as(ctypes.POINTER(ctype)))
                argument_types.append(ctypes.POINTER(ctype))
        self.native.argtypes = argument_types
        self.native.restype = None
        self.native(*arguments)
        self.front = back
        self.generation += 1
        return self.generation

    def display_plane(self) -> np.ndarray:
        """Acquire the current display plane, including target readback if needed."""

        if not self._outputs:
            raise RuntimeError("compiled program has no display output plane")
        return next(iter(self._outputs.values()))[self.front]

    def frame(self, elapsed: float) -> np.ndarray:
        self.execute(elapsed)
        return self.display_plane() if self._outputs else np.empty(0, dtype=np.uint8)

    def rgb(self, pixels: np.ndarray, elapsed: float) -> np.ndarray:
        display = next(
            request for request in self.manifest["requests"]
            if request["capability"] == "display_double_buffer"
        )
        attributes = display.get("attributes") or {}
        pixel_format = attributes.get("pixel_format", "rgba8")
        reshaped = pixels.reshape(self.height, self.width)
        if pixel_format == "indexed_float32":
            maximum = float(attributes.get(
                "maximum", self.options.get("iterations", 1)
            ))
            phase = elapsed * float(attributes.get("palette_rate", 0.03))
            normalized = np.sqrt(np.clip(reshaped / max(1.0, maximum), 0.0, 1.0))
            angle = 2.0 * np.pi * (normalized + phase)
            rgb = np.empty((self.height, self.width, 3), dtype=np.uint8)
            for channel, offset in enumerate((0.0, 2.094395102, 4.188790205)):
                rgb[..., channel] = np.asarray(
                    127.5 + 127.5 * np.cos(angle + offset), dtype=np.uint8
                )
            rgb[reshaped >= maximum] = 0
            return rgb
        if pixel_format == "rgb8":
            return pixels.reshape(self.height, self.width, 3)
        if pixel_format == "rgba8":
            return pixels.reshape(self.height, self.width, 4)[..., :3]
        raise ValueError(f"unsupported generated display format {pixel_format!r}")

    def close(self) -> None:
        if self.library is not None:
            import _ctypes

            handle = self.library._handle
            self.native = None
            self.library = None
            if os.name == "nt":
                _ctypes.FreeLibrary(handle)
            else:
                _ctypes.dlclose(handle)
        if self._dll_directory is not None:
            self._dll_directory.close()
            self._dll_directory = None


def launch_native_shell(
    api: Mapping[str, Any],
    library_path: str | Path,
    argv: Sequence[str] | None = None,
) -> int:
    if hasattr(api, "to_mapping"):
        api = api.to_mapping()
    manifest = api["metadata"]["shell_io"]["requirements"]
    args = _option_parser(manifest).parse_args(argv)
    options = vars(args)
    frame_limit = int(options.pop("frames"))
    headless = bool(options.pop("headless"))
    profile = bool(options.pop("profile"))
    ignore_transfer = bool(options.pop("profile_ignore_transfer"))
    profile_warmup = int(options.pop("profile_warmup"))
    if ignore_transfer and not profile:
        raise ValueError("--profile-ignore-transfer requires --profile")
    runtime = NativeShellRuntime(api, library_path, options)
    started = time.perf_counter()
    try:
        if profile:
            result = profile_frame_arrivals(
                runtime,
                arrivals=frame_limit or 120,
                warmup=profile_warmup,
                ignore_transfer=ignore_transfer,
                fps=float(options.get("fps", 30.0)),
            )
            print(json.dumps(result.to_mapping(), sort_keys=True))
            return 0
        has_display = any(
            request.get("capability") == "display_double_buffer"
            for request in manifest.get("requests", ())
        )
        if headless or not has_display:
            for index in range(frame_limit or 1):
                runtime.frame(index / float(options.get("fps", 30.0)))
            if has_display:
                print(
                    f"rendered {runtime.generation} frame(s), "
                    f"{runtime.width}x{runtime.height}"
                )
            else:
                print(f"executed {runtime.generation} generation(s)")
            return 0
        import pygame

        pygame.init()
        screen = pygame.display.set_mode(
            (runtime.width, runtime.height), pygame.DOUBLEBUF
        )
        clock = pygame.time.Clock()
        running = True
        while running and (frame_limit <= 0 or runtime.generation < frame_limit):
            for event in pygame.event.get():
                if event.type == pygame.QUIT:
                    running = False
                elif event.type == pygame.KEYDOWN:
                    if event.key in (pygame.K_ESCAPE, pygame.K_q):
                        running = False
                    runtime.keys |= 1 << (event.key & 31)
                elif event.type == pygame.KEYUP:
                    runtime.keys &= ~(1 << (event.key & 31))
                elif event.type == pygame.MOUSEMOTION:
                    runtime.pointer[:] = event.pos
                    runtime.buttons = sum(
                        int(down) << index
                        for index, down in enumerate(event.buttons)
                    )
            elapsed = time.perf_counter() - started
            pixels = runtime.frame(elapsed)
            surface = pygame.surfarray.make_surface(
                np.transpose(runtime.rgb(pixels, elapsed), (1, 0, 2))
            )
            screen.blit(surface, (0, 0))
            pygame.display.flip()
            pygame.display.set_caption(
                f"generated native shell | generation {runtime.generation}"
            )
            clock.tick(max(1.0, float(options.get("fps", 30.0))))
        pygame.quit()
        return 0
    finally:
        runtime.close()


def profile_frame_arrivals(
    runtime: Any,
    *,
    arrivals: int,
    warmup: int = 3,
    ignore_transfer: bool = False,
    fps: float = 30.0,
    clock_ns: Callable[[], int] = time.perf_counter_ns,
) -> ArrivalProfile:
    """Time gaps between completed generations without inspecting pixel data."""

    arrivals = int(arrivals)
    warmup = int(warmup)
    if arrivals < 2:
        raise ValueError("arrival profiling requires at least two frames")
    if warmup < 0:
        raise ValueError("profile warmup cannot be negative")
    operation = runtime.execute if ignore_transfer else runtime.frame
    rate = max(1.0, float(fps))
    for index in range(warmup):
        operation(index / rate)
    timestamps = []
    for index in range(arrivals):
        operation((warmup + index) / rate)
        timestamps.append(int(clock_ns()))
    gaps_ms = tuple(
        (current - previous) / 1_000_000.0
        for previous, current in zip(timestamps, timestamps[1:])
    )
    return ArrivalProfile(arrivals, warmup, bool(ignore_transfer), gaps_ms)


__all__ = [
    "GeneratedPythonShell",
    "CompiledNativeShell",
    "ArrivalProfile",
    "NativeShellRuntime",
    "NativeFilePortHandler",
    "NativeFilePortValue",
    "emit_python_native_shell",
    "compile_ast_fortran_io_shell",
    "compile_and_launch_ast_fortran_io",
    "launch_native_shell",
    "profile_frame_arrivals",
]
