"""Declarative Mandelbrot program for the generated Fortran IO shell.

This module contains application equations and an IO manifest only.  The CLI,
Fortran call adapter, event forwarding, double buffers, palette presentation,
and continuous loop are generated by ``compiler.python_native_shell``.
"""

from __future__ import annotations

from ....compiler.python_native_shell import compile_and_launch_ast_fortran_io
from ....compiler.shell_io import (
    ShellIOBinding,
    ShellIOCapability,
    ShellIOManifest,
    ShellIORequest,
    ShellOption,
)


SOURCE = """
def mandelbrot_frame(unit_x, unit_y, iterations):
    cx = unit_x * 1.5 - 0.75
    cy = unit_y
    zx = cx * 0.0
    zy = cx * 0.0
    count = cx * 0.0
    clamp_value = cx * 0.0 + 1e18
    for _ in range(iterations):
        zx2 = zx * zx
        zy2 = zy * zy
        count = count + (zx2 + zy2 <= 4.0)
        next_zx = zx2 - zy2 + cx
        next_zy = 2.0 * zx * zy + cy
        zx = next_zx.minimum(clamp_value).maximum(-clamp_value)
        zy = next_zy.minimum(clamp_value).maximum(-clamp_value)
    return count
"""


IO = ShellIOManifest(
    requests=(
        ShellIORequest.create(ShellIOCapability.KEYBOARD),
        ShellIORequest.create(ShellIOCapability.POINTER),
        ShellIORequest.create(
            ShellIOCapability.DISPLAY,
            attributes={
                "pixel_format": "indexed_float32",
                "buffers": 2,
                "palette_rate": 0.03,
            },
        ),
    ),
    bindings=(
        ShellIOBinding("display.unit_x", "mandelbrot_frame", "unit_x"),
        ShellIOBinding("display.unit_y", "mandelbrot_frame", "unit_y"),
        ShellIOBinding("option.iterations", "mandelbrot_frame", "iterations"),
        ShellIOBinding("display.back", "mandelbrot_frame", "count"),
    ),
    options=(
        ShellOption("width", "int", 640, "display width"),
        ShellOption("height", "int", 480, "display height"),
        ShellOption("iterations", "int", 96, "escape iterations per frame"),
        ShellOption("fps", "float", 30.0, "presentation frame limit"),
    ),
)


def main(argv=None) -> int:
    return compile_and_launch_ast_fortran_io(
        SOURCE, "mandelbrot_frame", IO, argv=argv
    )


if __name__ == "__main__":
    raise SystemExit(main())


__all__ = ["IO", "SOURCE", "main"]
