"""JPEG-specific adapters over the general tensor compression primitives."""

from .huffman import (
    JPEG_AC_CHROMINANCE_COUNTS,
    JPEG_AC_CHROMINANCE_SYMBOLS,
    JPEG_AC_LUMINANCE_COUNTS,
    JPEG_AC_LUMINANCE_SYMBOLS,
    JPEG_DC_CHROMINANCE_COUNTS,
    JPEG_DC_CHROMINANCE_SYMBOLS,
    JPEG_DC_LUMINANCE_COUNTS,
    JPEG_DC_LUMINANCE_SYMBOLS,
    jpeg_huffman_table,
    jpeg_standard_ac_chrominance,
    jpeg_standard_ac_luminance,
    jpeg_standard_dc_chrominance,
    jpeg_standard_dc_luminance,
)
from .transform import (
    JPEG_CHROMA_QUANTIZATION,
    JPEG_LUMA_QUANTIZATION,
    JPEG_ZIGZAG,
    jpeg_chroma_coefficients,
    jpeg_component_coefficients,
    jpeg_luma_coefficients,
    rgb_to_ycbcr,
)
from .scan import (
    JPEG_AC_CAPACITY,
    JPEG_ZRL,
    encode_baseline_color_scan,
    encode_baseline_luma_scan,
    jpeg_ac_entropy_symbols,
)
from .frame import (
    encode_color_jfif,
    encode_grayscale_jfif,
    encode_jfif,
    encode_ycbcr_jfif,
    iter_jfif_chunks,
    iter_ycbcr_jfif_chunks,
    write_grayscale_jfif,
    write_jfif,
)

__all__ = [
    "JPEG_AC_CHROMINANCE_COUNTS",
    "JPEG_AC_CHROMINANCE_SYMBOLS",
    "JPEG_AC_LUMINANCE_COUNTS",
    "JPEG_AC_LUMINANCE_SYMBOLS",
    "JPEG_DC_CHROMINANCE_COUNTS",
    "JPEG_DC_CHROMINANCE_SYMBOLS",
    "JPEG_DC_LUMINANCE_COUNTS",
    "JPEG_DC_LUMINANCE_SYMBOLS",
    "jpeg_huffman_table",
    "jpeg_standard_ac_chrominance",
    "jpeg_standard_ac_luminance",
    "jpeg_standard_dc_chrominance",
    "jpeg_standard_dc_luminance",
    "JPEG_CHROMA_QUANTIZATION",
    "JPEG_LUMA_QUANTIZATION",
    "JPEG_ZIGZAG",
    "JPEG_AC_CAPACITY",
    "JPEG_ZRL",
    "encode_baseline_color_scan",
    "encode_baseline_luma_scan",
    "encode_color_jfif",
    "encode_grayscale_jfif",
    "encode_jfif",
    "encode_ycbcr_jfif",
    "iter_jfif_chunks",
    "iter_ycbcr_jfif_chunks",
    "jpeg_ac_entropy_symbols",
    "jpeg_chroma_coefficients",
    "jpeg_component_coefficients",
    "jpeg_luma_coefficients",
    "rgb_to_ycbcr",
    "write_grayscale_jfif",
    "write_jfif",
]
